### ISSUE TITLE
Multiple functions for one hook are not split correctly

### ISSUE THREAD

**Issue by hcgraf** [willghatch/zsh-hooks#1]
Hi,

after adding two functions to the same hook like

```
hooks-add-hook zle_line_init_hook function1
hooks-add-hook zle_line_init_hook function2
```

I'm getting the error

```
hooks-run-hook:2: command not found: function1 function2
```

It is resolved when I remove the quotation marks in line 94 of `zsh-hooks.plugin.zsh`.

Is this a problem with my setup (IFS, some zsh-option set/unset)? Or is it generally save to remove those quotation marks?

Thanks!
Hagen

**Comment by willghatch** [comment]
I was a little over-zealous with quoting.   In practice I actually don't have more than one function per hook, so I hadn't noticed.  I'm a little embarrased that a piece of core functionality was obviously not working.  Thanks for pointing this out!
