### ISSUE TITLE
Give example of usage with `zle` hooks

### ISSUE THREAD

**Issue by HaleTom** [willghatch/zsh-hooks#5]
It took me a while to work out how to use this on the `zle` hooks. 

After hunting around the source and  `declare -f`, I offer this to be added to the README:

-----------

**Example**: Add a function `my_function` to run from `zle-line-init`:

```
hooks-add-hook zle_line_init_hook my_function
```
Note the underscores and addition of `_hook` in the hook variable name.

For the `zle` hooks, the `hook_variable_name`s are pre-added.

-------------

Here is an example of this at work:
```
% init(){echo -n '[zle init]'}; finish(){printf '[zle finish]'}
% hooks-add-hook zle_line_init_hook init
% [zle init]hooks-add-hook zle_line_finish_hook finish
% [zle init]date[zle finish]
Fri Jul 13 10:37:31 +07 2018
% [zle init] 
```

**Comment by willghatch** [comment]
I would have accepted a pull request as well ;)

At any rate, I wrote a shorter version of this.
